**Exercise 21**

The IRIS dataset was loaded into *data* and *target* variables. These datasets was spitted into the training set (*data_train, target_train*) and the test set (*data_test, target_test*).

Create a logistic regression model (set `max_iter=1000`) using *LogisticRegression*  from the *scikit-learn* package. Fit the model on the train set and then evaluate the model on the test set.

In response, print the accuracy of the model on the test set as shown below.

**Expected result:**
`Accuracy: 0.9333`

[Solution 21](https://www.notion.so/Solution-21-c33ae2fa81ae486db91bfc0f8a6af914?pvs=21)

In [9]:
# !pip install -U scikit-learn

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

print(sklearn.__version__)

data, target = datasets.load_iris(return_X_y=True)

data_train, data_test, target_train, target_test = sklearn.model_selection.train_test_split(
    data,
    target,
    test_size=0.3,
    random_state=20)

model = LogisticRegression(max_iter=1000).fit(data_train, target_train)

accuracy = model.score(data_test, target_test)
print(f"Accuracy: {accuracy:.4f}")

1.2.2
Accuracy: 0.9333


**Exercise 22**

The IRIS dataset was loaded into *data* and *target* variables. These datasets was spitted into the training set (*data_train, target_train*) and the test set (*data_test, target_test*).

The logistic regression model was built using *LogisticRegression* from the *scikit-learn* package.

Using this model make a prediction on the test set and assign to *target_pred* variable.

In response, print the *target_pred* variable to the console.

**Expected result:**

`[0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1 1 1 0 0 0 1 1 0 1 2 1 2 0 1 1]`

[Solution 22](https://www.notion.so/Solution-22-69d78dcc02c64584a3abe5fc00ec7e62?pvs=21)

In [11]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

print(sklearn.__version__)

data, target = datasets.load_iris(return_X_y=True)

data_train, data_test, target_train, target_test = sklearn.model_selection.train_test_split(
    data,
    target,
    test_size=0.3,
    random_state=20)

model = LogisticRegression(max_iter=1000).fit(data_train, target_train)

target_pred = model.predict(data_test)
print(target_pred)

1.2.2
[0 1 1 2 1 1 2 0 2 0 2 1 1 0 0 2 0 1 2 1 1 2 2 0 1 1 1 0 2 1 1 1 0 0 0 1 1
 0 1 2 1 2 0 1 1]


**Exercise 23**

The IRIS dataset was loaded into *data* and *target* variables. These datasets was spitted into the training set (*data_train, target_train*) and the test set (*data_test, target_test*). The logistic regression model was built using the *scikit-learn* package.

Predictions on the test set was assigned to the variable *target_pred*.

Using *scikit-learn* package specify the confusion matrix (`confusion_matrix()`) and print it to the console as shown below.

**Expected result:**

 `[[13  0  0]
   [ 0 18  0]
   [ 0  3 11]]`

[Solution 23](https://www.notion.so/Solution-23-6687f4b1a9884d5ab7b58ce4110aca35?pvs=21)

In [7]:
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

data, target = sklearn.datasets.load_iris(return_X_y=True)

data_train, data_test, target_train, target_test = sklearn.model_selection.train_test_split(
    data,
    target,
    test_size=0.3,
    random_state=20)

model = LogisticRegression(max_iter=1000).fit(data_train, target_train)
target_pred = model.predict(data_test)

confusion_matrix(target_test, target_pred)

array([[13,  0,  0],
       [ 0, 18,  0],
       [ 0,  3, 11]])

**Exercise 24**

The IRIS dataset was loaded into *data* and *target* variables. These datasets was spitted into the training set (*data_train, target_train*) and the test set (*data_test, target_test*). The logistic regression model was built using the *scikit-learn* package.

Predictions on the test set was assigned to the variable *target_pred*.

Print the classification report using the `classification_report()` function from the *scikit-learn* package to the console.

**Expected result:**

```python
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.86      1.00      0.92        18
           2       1.00      0.79      0.88        14

    accuracy                           0.93        45
   macro avg       0.95      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45
```

[Solution 24](https://www.notion.so/Solution-24-af704f0aa04741a99a92e0a21cdfdeeb?pvs=21)

In [15]:
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

data, target = datasets.load_iris(return_X_y=True)

data_train, data_test, target_train, target_test = train_test_split(
    data,
    target,
    test_size=0.3,
    random_state=20)

model = LogisticRegression(max_iter=1000)
model.fit(data_train, target_train)

target_pred = model.predict(data_test)

report = sklearn.metrics.classification_report(target_test, target_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.86      1.00      0.92        18
           2       1.00      0.79      0.88        14

    accuracy                           0.93        45
   macro avg       0.95      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45



**Exercise 25**

The *df* *DataFrame* is given below:

```python
  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes
```

Using the *LabelEncoder* class from the *scikit-learn* package encode target variable - *bought* as shown below and assign the result to the *df DataFrame*.

In response, print the *df DataFrame* to the console.

**Expected result:**

```python
  size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1
```

[Solution 25](https://www.notion.so/Solution-25-f0fcaf39757043f18c1aebf14ca94741?pvs=21)

In [37]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df = pd.DataFrame(data)
df["bought"] = LabelEncoder().fit_transform(data["bought"])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0     500       1
1    L  green    male   89.0     450       0
2    M   blue    male   99.0     300       1
3    L  green  female  129.0     380       0
4    M    red  female   79.0     410       1

**Exercise 26**

The *df* *DataFrame* is given below:

```python
  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes
```

Using the *OneHotEncoder* from the *scikit-learn* package, encode the *size* column as a one-hot numeric array. (set the parameter `sparse=False`).

In response, print the encoded *size* column to the console (don't assign changes to the *df DataFrame*). Also print the encoding categories to the console as shown below.

**Expected result:**

```python
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[array(['L', 'M', 'XL'], dtype=object)]
```

[Solution 26](https://www.notion.so/Solution-26-a95eeb7ab9ac42e88c91afdf3674209b?pvs=21)

In [54]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df = pd.DataFrame(data)

onehotencoder = OneHotEncoder(sparse_output=False)
onehotencoder.fit(df[["size"]])
transformed_size = onehotencoder.transform(df[["size"]])

print(transformed_size)
print(onehotencoder.categories_)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[array(['L', 'M', 'XL'], dtype=object)]


**Exercise 27**

Load Breast Cancer Data using the `load_breast_cancer()` function from the *scikit-learn* package into the *raw_data* variable. Then print information about this dataset to the console (the content of the `'DESCR'` key) as shown below.

**Expected result:**

```python
.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radius, field
        10 is Radius SE, field 20 is Worst Radius.

        - class:
                - WDBC-Malignant
                - WDBC-Benign

    :Summary Statistics:

    ===================================== ====== ======
                                           Min    Max
    ===================================== ====== ======
    radius (mean):                        6.981  28.11
    texture (mean):                       9.71   39.28
    perimeter (mean):                     43.79  188.5
    area (mean):                          143.5  2501.0
    smoothness (mean):                    0.053  0.163
    compactness (mean):                   0.019  0.345
    concavity (mean):                     0.0    0.427
    concave points (mean):                0.0    0.201
    symmetry (mean):                      0.106  0.304
    fractal dimension (mean):             0.05   0.097
    radius (standard error):              0.112  2.873
    texture (standard error):             0.36   4.885
    perimeter (standard error):           0.757  21.98
    area (standard error):                6.802  542.2
    smoothness (standard error):          0.002  0.031
    compactness (standard error):         0.002  0.135
    concavity (standard error):           0.0    0.396
    concave points (standard error):      0.0    0.053
    symmetry (standard error):            0.008  0.079
    fractal dimension (standard error):   0.001  0.03
    radius (worst):                       7.93   36.04
    texture (worst):                      12.02  49.54
    perimeter (worst):                    50.41  251.2
    area (worst):                         185.2  4254.0
    smoothness (worst):                   0.071  0.223
    compactness (worst):                  0.027  1.058
    concavity (worst):                    0.0    1.252
    concave points (worst):               0.0    0.291
    symmetry (worst):                     0.156  0.664
    fractal dimension (worst):            0.055  0.208
    ===================================== ====== ======

    :Missing Attribute Values: None

    :Class Distribution: 212 - Malignant, 357 - Benign

    :Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

    :Donor: Nick Street

    :Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. topic:: References

   - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
     for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
     Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
     San Jose, CA, 1993.
   - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
     prognosis via linear programming. Operations Research, 43(4), pages 570-577,
     July-August 1995.
   - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
     to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
     163-171.        
```

[Solution 27](https://www.notion.so/Solution-27-37f2e5ec9d1340e08c8af42790acbc6d?pvs=21)

In [55]:
from sklearn import datasets

raw_data = datasets.load_breast_cancer()

print(raw_data["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

**Exercise 28**

The Breast Cancer Data was loaded into the *raw_data* variable.

Assign the value for the `'data'` key (*numpy* array) to the *data* variable. Then assign the value for the `'target'` key (*numpy* array) to the *target* variable*.*

In response, print the first three elements of the *data* array to the console.

**Expected result:**

```python
[[  17.99   10.38  122.8  1001.      0.12    0.28    0.3     0.15    0.24    0.08    1.09    0.91
     8.59  153.4     0.01    0.05    0.05    0.02    0.03    0.01   25.38   17.33  184.6  2019.
     0.16    0.67    0.71    0.27    0.46    0.12]
 [  20.57   17.77  132.9  1326.      0.08    0.08    0.09    0.07    0.18    0.06    0.54    0.73
     3.4    74.08    0.01    0.01    0.02    0.01    0.01    0.     24.99   23.41  158.8  1956.
     0.12    0.19    0.24    0.19    0.28    0.09]
 [  19.69   21.25  130.   1203.      0.11    0.16    0.2     0.13    0.21    0.06    0.75    0.79
     4.58   94.03    0.01    0.04    0.04    0.02    0.02    0.     23.57   25.53  152.5  1709.
     0.14    0.42    0.45    0.24    0.36    0.09]]
```

[Solution 28](https://www.notion.so/Solution-28-5a202e1047fb4c62bb3827a1872c4e49?pvs=21)

In [63]:
from sklearn import datasets
import numpy as np

raw_data = datasets.load_breast_cancer()

data = raw_data["data"]
target = raw_data["target"]

np.set_printoptions(precision=2, suppress=True)
print(data[:3])

[[  17.99   10.38  122.8  1001.      0.12    0.28    0.3     0.15    0.24
     0.08    1.09    0.91    8.59  153.4     0.01    0.05    0.05    0.02
     0.03    0.01   25.38   17.33  184.6  2019.      0.16    0.67    0.71
     0.27    0.46    0.12]
 [  20.57   17.77  132.9  1326.      0.08    0.08    0.09    0.07    0.18
     0.06    0.54    0.73    3.4    74.08    0.01    0.01    0.02    0.01
     0.01    0.     24.99   23.41  158.8  1956.      0.12    0.19    0.24
     0.19    0.28    0.09]
 [  19.69   21.25  130.   1203.      0.11    0.16    0.2     0.13    0.21
     0.06    0.75    0.79    4.58   94.03    0.01    0.04    0.04    0.02
     0.02    0.     23.57   25.53  152.5  1709.      0.14    0.42    0.45
     0.24    0.36    0.09]]


**Exercise 29**

The Breast Cancer Data was loaded into the *data* and *target* variables.

Combine these two arrays into one array, assign to *all_data* variable and print the first three rows of this array to the console.

**Expected result:**

```python
[[  17.99   10.38  122.8  1001.      0.12    0.28    0.3     0.15    0.24    0.08    1.09    0.91
     8.59  153.4     0.01    0.05    0.05    0.02    0.03    0.01   25.38   17.33  184.6  2019.
     0.16    0.67    0.71    0.27    0.46    0.12    0.  ]
 [  20.57   17.77  132.9  1326.      0.08    0.08    0.09    0.07    0.18    0.06    0.54    0.73
     3.4    74.08    0.01    0.01    0.02    0.01    0.01    0.     24.99   23.41  158.8  1956.
     0.12    0.19    0.24    0.19    0.28    0.09    0.  ]
 [  19.69   21.25  130.   1203.      0.11    0.16    0.2     0.13    0.21    0.06    0.75    0.79
     4.58   94.03    0.01    0.04    0.04    0.02    0.02    0.     23.57   25.53  152.5  1709.
     0.14    0.42    0.45    0.24    0.36    0.09    0.  ]]
```

[Solution 29](https://www.notion.so/Solution-29-e1dcd264041f4d9eaa1c9db3707bcbce?pvs=21)

In [72]:
from sklearn import datasets
import numpy as np

raw_data = datasets.load_breast_cancer()

data = raw_data["data"]
target = raw_data["target"]

np.set_printoptions(precision=2, suppress=True)

all_data = np.column_stack((data, target))
all_data[:3]

array([[  17.99,   10.38,  122.8 , 1001.  ,    0.12,    0.28,    0.3 ,
           0.15,    0.24,    0.08,    1.09,    0.91,    8.59,  153.4 ,
           0.01,    0.05,    0.05,    0.02,    0.03,    0.01,   25.38,
          17.33,  184.6 , 2019.  ,    0.16,    0.67,    0.71,    0.27,
           0.46,    0.12,    0.  ],
       [  20.57,   17.77,  132.9 , 1326.  ,    0.08,    0.08,    0.09,
           0.07,    0.18,    0.06,    0.54,    0.73,    3.4 ,   74.08,
           0.01,    0.01,    0.02,    0.01,    0.01,    0.  ,   24.99,
          23.41,  158.8 , 1956.  ,    0.12,    0.19,    0.24,    0.19,
           0.28,    0.09,    0.  ],
       [  19.69,   21.25,  130.  , 1203.  ,    0.11,    0.16,    0.2 ,
           0.13,    0.21,    0.06,    0.75,    0.79,    4.58,   94.03,
           0.01,    0.04,    0.04,    0.02,    0.02,    0.  ,   23.57,
          25.53,  152.5 , 1709.  ,    0.14,    0.42,    0.45,    0.24,
           0.36,    0.09,    0.  ]])

**Exercise 30**

The Breast Cancer Data was loaded into the *all_data* variable.

Create a *DataFrame* from the *all_data* array and assign to *df* variable. Set column names using value for the key `'feature_names'` of *raw_data* + set target variable name as `'target'` as shown below.

In response, print the first five rows of this *DataFrame* to the console.

**Expected result:**

```python
 mean radius  mean texture  mean perimeter  mean area  mean smoothness  ...  worst concavity  worst concave points  worst symmetry  worst fractal dimension  target
0        17.99         10.38          122.80     1001.0          0.11840  ...           0.7119                0.2654          0.4601                  0.11890     0.0
1        20.57         17.77          132.90     1326.0          0.08474  ...           0.2416                0.1860          0.2750                  0.08902     0.0
2        19.69         21.25          130.00     1203.0          0.10960  ...           0.4504                0.2430          0.3613                  0.08758     0.0
3        11.42         20.38           77.58      386.1          0.14250  ...           0.6869                0.2575          0.6638                  0.17300     0.0
4        20.29         14.34          135.10     1297.0          0.10030  ...           0.4000                0.1625          0.2364                  0.07678     0.0

[5 rows x 31 columns]

```

[Solution 30](https://www.notion.so/Solution-30-208e8346f9464962a519c29194532f4e?pvs=21)

In [87]:
#ТЗ странное. Непонятно, какая переменная откуда должна выходить.

from sklearn import datasets
import pandas as pd

pd.set_option('display.max_columns', 10)
pd.set_option('display.width', 200)
np.set_printoptions(precision=2, suppress=True, linewidth=100)
raw_data = datasets.load_breast_cancer()

data = raw_data['data']
target = raw_data['target']

all_data = np.c_[data, target]
df = pd.DataFrame(
    data=all_data,
    columns=list(raw_data['feature_names']) + ['target']
)
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  ...  worst concavity  worst concave points  worst symmetry  worst fractal dimension  target
0        17.99         10.38          122.80     1001.0          0.11840  ...           0.7119                0.2654          0.4601                  0.11890     0.0
1        20.57         17.77          132.90     1326.0          0.08474  ...           0.2416                0.1860          0.2750                  0.08902     0.0
2        19.69         21.25          130.00     1203.0          0.10960  ...           0.4504                0.2430          0.3613                  0.08758     0.0
3        11.42         20.38           77.58      386.1          0.14250  ...           0.6869                0.2575          0.6638                  0.17300     0.0
4        20.29         14.34          135.10     1297.0          0.10030  ...           0.4000                0.1625          0.2364                  0.07678     0.0

[5 

**Exercise 31**

The Breast Cancer Data was loaded into the *data* and *target* variables.

Using the `train_test_split()` function from the *scikit-learn* package, split the data (*data* and *target*) into train and test sets:

- train set: `X_train, y_train`
- test set: `X_test, y_test`

Set the `random_state=40` and the test set size to 25%.

In response, print the shapes of these arrays to the console as shown below.

```python
X_train shape (426, 30)
y_train shape (426,)
X_test shape (143, 30)
y_test shape (143,)
```

[Solution 31](https://www.notion.so/Solution-31-d5259ff6894848d0ba16c3b79e96a4d4?pvs=21)

In [95]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

data, target = datasets.load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
    data,
    target,
    test_size=0.25,
    random_state=40)

print("X_train shape {}".format(X_train.shape))
print("y_train shape {}".format(y_train.shape))
print("X_test shape {}".format(X_test.shape))
print("y_test shape {}".format(y_test.shape))

X_train shape (426, 30)
y_train shape (426,)
X_test shape (143, 30)
y_test shape (143,)
