In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=4, suppress=True)

data = pd.read_csv("/content/sample_data/Utility_sklearn.csv")
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[-0.4785, -0.2137, -0.4584, -0.5114,  0.0636],
       [ 1.3742,  0.3895,  1.2924,  1.4055, -0.616 ],
       [ 0.3777, -0.0178,  0.3905,  0.2783,  0.7424],
       [-0.4986, -0.4185, -0.4427, -0.5531,  0.4723],
       [-0.7449, -1.1397, -0.7236, -0.745 ,  0.0771],
       [ 1.8496,  2.1747,  1.9719,  1.8048,  1.3537],
       [ 2.2534,  0.5208,  2.2644,  2.4466,  0.5363],
       [ 0.9819, -1.0039,  0.9382,  0.8882, -0.0203],
       [-0.2294, -0.8236, -0.236 , -0.3987,  0.6429],
       [-0.069 , -0.6544, -0.1338, -0.1639, -2.1663],
       [-0.2666,  1.2665, -0.3344, -0.3457, -0.7709],
       [ 0.7557, -0.1692,  0.7035,  0.6847, -0.7183],
       [ 0.2374,  0.0445,  0.1351,  0.1047, -1.0339],
       [ 0.6068,  0.5164,  0.6293,  0.5087,  1.2613],
       [-0.5158, -1.6227, -0.5469, -0.551 , -0.6202],
       [ 1.4201,  1.498 ,  1.5189,  1.4114,  1.6167],
       [ 0.1916, -1.0818,  0.1005,  0.0766, -0.9977],
       [-1.14  ,  0.0066, -1.1321, -1.0148,  0.1098],
       [-2.0504, -1.3645, -1

# 43

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

X_train = pd.read_csv("/content/Sklearn_X_train.csv")
X_test = pd.read_csv("/content/sklearn_X_test.csv")

scaler = StandardScaler()
scaler.fit(X_train)


print(scaler.transform(X_train)[:5])
print(scaler.transform(X_test)[:5])

[[-0.3491 -1.4385 -0.4117 -0.3905 -1.8637]
 [-0.2047  0.3126 -0.1337 -0.2759  1.0781]
 [-0.3293 -0.2151 -0.3174 -0.3644 -1.5799]
 [ 1.0274  2.0898  1.0469  0.9176  0.3163]
 [ 1.829   0.696   1.7637  1.7838 -0.3337]]
[[-0.4681 -0.1417 -0.4447 -0.486   0.2934]
 [ 1.3645  0.4996  1.3064  1.3344 -0.3917]
 [ 0.3788  0.0665  0.4043  0.264   0.9777]
 [-0.4879 -0.3594 -0.429  -0.5256  0.7054]
 [-0.7315 -1.1261 -0.71   -0.7079  0.307 ]]


# 44

In [14]:
import numpy as np
import pandas as pd


def entropy(x):
    print(x)
    return np.round(-np.sum(x * np.log2(x)), 4)


data_dict = {
    'val_1': np.arange(0.01, 1.0, 0.1),
    'val_2': 1 - np.arange(0.01, 1.0, 0.1)
}
df = pd.DataFrame(data_dict)

df['entropy'] = [
    entropy([row[1][0], row[1][1]])
    for row in df.iterrows()
]

[0.01, 0.99]
[0.11, 0.89]
[0.21000000000000002, 0.79]
[0.31000000000000005, 0.69]
[0.41000000000000003, 0.59]
[0.51, 0.49]
[0.6100000000000001, 0.3899999999999999]
[0.7100000000000001, 0.2899999999999999]
[0.81, 0.18999999999999995]
[0.91, 0.08999999999999997]


45

In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

np.set_printoptions(suppress=True, precision=4)

df = pd.read_csv("/content/predictions.csv")
y_true = df["y_true"]
y_pred = df["y_pred"]

print(round(accuracy_score(y_true, y_pred), 4))

0.7241


46

In [12]:
from sklearn.metrics import confusion_matrix

df = pd.read_csv("predictions46.csv")
print(confusion_matrix(df["y_true"], df["y_pred"]))

[[ 6  1  0]
 [ 3 10  2]
 [ 0  2  5]]


47

In [16]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
classifier.score(X_test, y_test)
# y_pred = classifier.predict(X_test)
# accuracy_score(y_test, y_pred)

0.902

48

In [17]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

cls = DecisionTreeClassifier(max_depth=6)
cls.fit(X_train, y_train)
cls.score(X_test, y_test)

0.928

49

In [21]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

cls = DecisionTreeClassifier(max_depth=6, min_samples_leaf=6)
cls.fit(X_train, y_train)
acc = cls.score(X_test, y_test)
print(f'{acc:.4f}')

0.9300


50

In [30]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

cls = DecisionTreeClassifier()
param_grid = [{"max_depth": np.arange(1, 10), "min_samples_leaf": [1,2,3,4,5,6,7,8,9,10,15,20]}]
grsearch = GridSearchCV(cls, scoring="accuracy", param_grid=param_grid, cv=5)
grsearch.fit(X_train, y_train)
grsearch.best_params_

{'max_depth': 6, 'min_samples_leaf': 6}